/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: log_logstores.proto */

#ifndef PROTOBUF_C_log_5flogstores_2eproto__INCLUDED
#define PROTOBUF_C_log_5flogstores_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _LogLogstores__Log LogLogstores__Log;
typedef struct _LogLogstores__Log__Content LogLogstores__Log__Content;
typedef struct _LogLogstores__LogGroup LogLogstores__LogGroup;


/* --- enums --- */


/* --- messages --- */

struct  _LogLogstores__Log__Content
{
  ProtobufCMessage base;
  char *key;
  char *value;
};
#define LOG_LOGSTORES__LOG__CONTENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&log_logstores__log__content__descriptor) \
    , NULL, NULL }


struct  _LogLogstores__Log
{
  ProtobufCMessage base;
  /*
   * UNIX Time Format
   */
  uint32_t time;
  size_t n_contents;
  LogLogstores__Log__Content **contents;
};
#define LOG_LOGSTORES__LOG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&log_logstores__log__descriptor) \
    , 0, 0,NULL }


struct  _LogLogstores__LogGroup
{
  ProtobufCMessage base;
  size_t n_logs;    
  LogLogstores__Log **logs;
  /*
   * 内部字段，不需要填写
   */
  char *reserved;
  char *topic;
  char *source;
};
#define LOG_LOGSTORES__LOG_GROUP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&log_logstores__log_group__descriptor) \
    , 0,NULL, NULL, NULL, NULL }


/* LogLogstores__Log__Content methods */
void   log_logstores__log__content__init
                     (LogLogstores__Log__Content         *message);
/* LogLogstores__Log methods */
void   log_logstores__log__init
                     (LogLogstores__Log         *message);
size_t log_logstores__log__get_packed_size
                     (const LogLogstores__Log   *message);
size_t log_logstores__log__pack
                     (const LogLogstores__Log   *message,
                      uint8_t             *out);
size_t log_logstores__log__pack_to_buffer
                     (const LogLogstores__Log   *message,
                      ProtobufCBuffer     *buffer);
LogLogstores__Log *
       log_logstores__log__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   log_logstores__log__free_unpacked
                     (LogLogstores__Log *message,
                      ProtobufCAllocator *allocator);
/* LogLogstores__LogGroup methods */
void   log_logstores__log_group__init
                     (LogLogstores__LogGroup         *message);
size_t log_logstores__log_group__get_packed_size
                     (const LogLogstores__LogGroup   *message);
size_t log_logstores__log_group__pack
                     (const LogLogstores__LogGroup   *message,
                      uint8_t             *out);
size_t log_logstores__log_group__pack_to_buffer
                     (const LogLogstores__LogGroup   *message,
                      ProtobufCBuffer     *buffer);
LogLogstores__LogGroup *
       log_logstores__log_group__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   log_logstores__log_group__free_unpacked
                     (LogLogstores__LogGroup *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*LogLogstores__Log__Content_Closure)
                 (const LogLogstores__Log__Content *message,
                  void *closure_data);
typedef void (*LogLogstores__Log_Closure)
                 (const LogLogstores__Log *message,
                  void *closure_data);
typedef void (*LogLogstores__LogGroup_Closure)
                 (const LogLogstores__LogGroup *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor log_logstores__log__descriptor;
extern const ProtobufCMessageDescriptor log_logstores__log__content__descriptor;
extern const ProtobufCMessageDescriptor log_logstores__log_group__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_log_5flogstores_2eproto__INCLUDED */
