/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sls_logstores.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "sls_logstores.pb-c.h"
void   sls_logstores__log__content__init
                     (SlsLogstores__Log__Content         *message)
{
  static SlsLogstores__Log__Content init_value = SLS_LOGSTORES__LOG__CONTENT__INIT;
  *message = init_value;
}
void   sls_logstores__log__init
                     (SlsLogstores__Log         *message)
{
  static SlsLogstores__Log init_value = SLS_LOGSTORES__LOG__INIT;
  *message = init_value;
}
size_t sls_logstores__log__get_packed_size
                     (const SlsLogstores__Log *message)
{
  assert(message->base.descriptor == &sls_logstores__log__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sls_logstores__log__pack
                     (const SlsLogstores__Log *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sls_logstores__log__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sls_logstores__log__pack_to_buffer
                     (const SlsLogstores__Log *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sls_logstores__log__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SlsLogstores__Log *
       sls_logstores__log__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SlsLogstores__Log *)
     protobuf_c_message_unpack (&sls_logstores__log__descriptor,
                                allocator, len, data);
}
void   sls_logstores__log__free_unpacked
                     (SlsLogstores__Log *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &sls_logstores__log__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   sls_logstores__log_group__init
                     (SlsLogstores__LogGroup         *message)
{
  static SlsLogstores__LogGroup init_value = SLS_LOGSTORES__LOG_GROUP__INIT;
  *message = init_value;
}
size_t sls_logstores__log_group__get_packed_size
                     (const SlsLogstores__LogGroup *message)
{
  assert(message->base.descriptor == &sls_logstores__log_group__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sls_logstores__log_group__pack
                     (const SlsLogstores__LogGroup *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sls_logstores__log_group__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sls_logstores__log_group__pack_to_buffer
                     (const SlsLogstores__LogGroup *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sls_logstores__log_group__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SlsLogstores__LogGroup *
       sls_logstores__log_group__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SlsLogstores__LogGroup *)
     protobuf_c_message_unpack (&sls_logstores__log_group__descriptor,
                                allocator, len, data);
}
void   sls_logstores__log_group__free_unpacked
                     (SlsLogstores__LogGroup *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &sls_logstores__log_group__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor sls_logstores__log__content__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SlsLogstores__Log__Content, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SlsLogstores__Log__Content, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sls_logstores__log__content__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange sls_logstores__log__content__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sls_logstores__log__content__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sls_logstores.Log.Content",
  "Content",
  "SlsLogstores__Log__Content",
  "sls_logstores",
  sizeof(SlsLogstores__Log__Content),
  2,
  sls_logstores__log__content__field_descriptors,
  sls_logstores__log__content__field_indices_by_name,
  1,  sls_logstores__log__content__number_ranges,
  (ProtobufCMessageInit) sls_logstores__log__content__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sls_logstores__log__field_descriptors[2] =
{
  {
    "time",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(SlsLogstores__Log, time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "contents",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SlsLogstores__Log, n_contents),
    offsetof(SlsLogstores__Log, contents),
    &sls_logstores__log__content__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sls_logstores__log__field_indices_by_name[] = {
  1,   /* field[1] = contents */
  0,   /* field[0] = time */
};
static const ProtobufCIntRange sls_logstores__log__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sls_logstores__log__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sls_logstores.Log",
  "Log",
  "SlsLogstores__Log",
  "sls_logstores",
  sizeof(SlsLogstores__Log),
  2,
  sls_logstores__log__field_descriptors,
  sls_logstores__log__field_indices_by_name,
  1,  sls_logstores__log__number_ranges,
  (ProtobufCMessageInit) sls_logstores__log__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor sls_logstores__log_group__field_descriptors[4] =
{
  {
    "logs",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(SlsLogstores__LogGroup, n_logs),
    offsetof(SlsLogstores__LogGroup, logs),
    &sls_logstores__log__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reserved",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SlsLogstores__LogGroup, reserved),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "topic",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SlsLogstores__LogGroup, topic),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "source",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SlsLogstores__LogGroup, source),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sls_logstores__log_group__field_indices_by_name[] = {
  0,   /* field[0] = logs */
  1,   /* field[1] = reserved */
  3,   /* field[3] = source */
  2,   /* field[2] = topic */
};
static const ProtobufCIntRange sls_logstores__log_group__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor sls_logstores__log_group__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "sls_logstores.LogGroup",
  "LogGroup",
  "SlsLogstores__LogGroup",
  "sls_logstores",
  sizeof(SlsLogstores__LogGroup),
  4,
  sls_logstores__log_group__field_descriptors,
  sls_logstores__log_group__field_indices_by_name,
  1,  sls_logstores__log_group__number_ranges,
  (ProtobufCMessageInit) sls_logstores__log_group__init,
  NULL,NULL,NULL    /* reserved[123] */
};
