/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: sls_logstores.proto */

#ifndef PROTOBUF_C_sls_5flogstores_2eproto__INCLUDED
#define PROTOBUF_C_sls_5flogstores_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _SlsLogstores__Log SlsLogstores__Log;
typedef struct _SlsLogstores__Log__Content SlsLogstores__Log__Content;
typedef struct _SlsLogstores__LogGroup SlsLogstores__LogGroup;


/* --- enums --- */


/* --- messages --- */

struct  _SlsLogstores__Log__Content
{
  ProtobufCMessage base;
  char *key;
  char *value;
};
#define SLS_LOGSTORES__LOG__CONTENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sls_logstores__log__content__descriptor) \
    , NULL, NULL }


struct  _SlsLogstores__Log
{
  ProtobufCMessage base;
  /*
   * UNIX Time Format
   */
  uint32_t time;
  size_t n_contents;
  SlsLogstores__Log__Content **contents;
};
#define SLS_LOGSTORES__LOG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sls_logstores__log__descriptor) \
    , 0, 0,NULL }


struct  _SlsLogstores__LogGroup
{
  ProtobufCMessage base;
  size_t n_logs;    
  SlsLogstores__Log **logs;
  /*
   * 内部字段，不需要填写
   */
  char *reserved;
  char *topic;
  char *source;
};
#define SLS_LOGSTORES__LOG_GROUP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&sls_logstores__log_group__descriptor) \
    , 0,NULL, NULL, NULL, NULL }


/* SlsLogstores__Log__Content methods */
void   sls_logstores__log__content__init
                     (SlsLogstores__Log__Content         *message);
/* SlsLogstores__Log methods */
void   sls_logstores__log__init
                     (SlsLogstores__Log         *message);
size_t sls_logstores__log__get_packed_size
                     (const SlsLogstores__Log   *message);
size_t sls_logstores__log__pack
                     (const SlsLogstores__Log   *message,
                      uint8_t             *out);
size_t sls_logstores__log__pack_to_buffer
                     (const SlsLogstores__Log   *message,
                      ProtobufCBuffer     *buffer);
SlsLogstores__Log *
       sls_logstores__log__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sls_logstores__log__free_unpacked
                     (SlsLogstores__Log *message,
                      ProtobufCAllocator *allocator);
/* SlsLogstores__LogGroup methods */
void   sls_logstores__log_group__init
                     (SlsLogstores__LogGroup         *message);
size_t sls_logstores__log_group__get_packed_size
                     (const SlsLogstores__LogGroup   *message);
size_t sls_logstores__log_group__pack
                     (const SlsLogstores__LogGroup   *message,
                      uint8_t             *out);
size_t sls_logstores__log_group__pack_to_buffer
                     (const SlsLogstores__LogGroup   *message,
                      ProtobufCBuffer     *buffer);
SlsLogstores__LogGroup *
       sls_logstores__log_group__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   sls_logstores__log_group__free_unpacked
                     (SlsLogstores__LogGroup *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*SlsLogstores__Log__Content_Closure)
                 (const SlsLogstores__Log__Content *message,
                  void *closure_data);
typedef void (*SlsLogstores__Log_Closure)
                 (const SlsLogstores__Log *message,
                  void *closure_data);
typedef void (*SlsLogstores__LogGroup_Closure)
                 (const SlsLogstores__LogGroup *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor sls_logstores__log__descriptor;
extern const ProtobufCMessageDescriptor sls_logstores__log__content__descriptor;
extern const ProtobufCMessageDescriptor sls_logstores__log_group__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_sls_5flogstores_2eproto__INCLUDED */
